README.md
=> chore: build status to development and make development default

app/src/main/java/com/mifos/apache/fineract/ui/adapters/CustomerAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/customer/CustomersContract.java, app/src/main/java/com/mifos/apache/fineract/ui/customer/CustomersFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/customer/CustomersPresenter.java, app/src/main/res/values/strings.xml
=> Feature: customer load more

app/src/main/AndroidManifest.xml, app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerDeposit.java, app/src/main/java/com/mifos/apache/fineract/data/models/State.java, app/src/main/java/com/mifos/apache/fineract/data/models/deposit/CustomerDepositAccounts.java, app/src/main/java/com/mifos/apache/fineract/data/remote/BaseApiManager.java, app/src/main/java/com/mifos/apache/fineract/data/remote/EndPoints.java, app/src/main/java/com/mifos/apache/fineract/data/services/DepositService.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ApplicationComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/CustomerDepositAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/customerdeposit/CustomerDepositActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/customerdeposit/CustomerDepositContract.java, app/src/main/java/com/mifos/apache/fineract/ui/customerdeposit/CustomerDepositFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/customerdeposit/CustomerDepositPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/customerdetails/CustomerDetailsFragment.java, app/src/main/res/drawable/round_corner.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_toolbar_container.xml, app/src/main/res/layout/fragment_customer_deposit.xml, app/src/main/res/layout/fragment_customer_details.xml, app/src/main/res/layout/item_customer_deposit_accounts.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
=> feat: customer deposit accounts

app/src/main/AndroidManifest.xml, app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerLoans.java, app/src/main/java/com/mifos/apache/fineract/data/models/loan/AccountAssignment.java, app/src/main/java/com/mifos/apache/fineract/data/models/loan/LoanAccount.java, app/src/main/java/com/mifos/apache/fineract/data/models/loan/LoanAccountPage.java, app/src/main/java/com/mifos/apache/fineract/data/remote/BaseApiManager.java, app/src/main/java/com/mifos/apache/fineract/data/remote/EndPoints.java, app/src/main/java/com/mifos/apache/fineract/data/services/LoanService.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ApplicationComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/CustomerLoanAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/base/DateUtils.java, app/src/main/java/com/mifos/apache/fineract/ui/customerdetails/CustomerDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/customerloans/CustomerLoansActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/customerloans/CustomerLoansContract.java, app/src/main/java/com/mifos/apache/fineract/ui/customerloans/CustomerLoansFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/customerloans/CustomerLoansPresenter.java, app/src/main/res/layout/fragment_customer_loans.xml, app/src/main/res/layout/item_customer_loans.xml, app/src/main/res/values/strings.xml
=> feat: customer loans

app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerLoans.java, app/src/main/java/com/mifos/apache/fineract/data/models/State.java, app/src/main/java/com/mifos/apache/fineract/data/models/loan/CreditWorthinessFactor.java, app/src/main/java/com/mifos/apache/fineract/data/models/loan/CreditWorthinessSnapshot.java, app/src/main/java/com/mifos/apache/fineract/data/models/loan/LoanAccount.java, app/src/main/java/com/mifos/apache/fineract/data/models/loan/LoanParameters.java, app/src/main/java/com/mifos/apache/fineract/data/models/loan/PaymentCycle.java, app/src/main/java/com/mifos/apache/fineract/data/models/loan/TermRange.java, app/src/main/java/com/mifos/apache/fineract/data/services/LoanService.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/customerloans/CustomerLoansFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/loandetails/CustomerLoanDetailsContract.java, app/src/main/java/com/mifos/apache/fineract/ui/loandetails/CustomerLoanDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/loandetails/CustomerLoanDetailsPresenter.java, app/src/main/java/com/mifos/apache/fineract/utils/ConstantKeys.java, app/src/main/res/drawable/ic_access_time_black_24dp.xml, app/src/main/res/drawable/ic_account_balance_black_24dp.xml, app/src/main/res/drawable/ic_done_all_black_24dp.xml, app/src/main/res/drawable/ic_edit_black_24dp.xml, app/src/main/res/drawable/ic_error_black_24dp.xml, app/src/main/res/drawable/ic_show_chart_black_24dp.xml, app/src/main/res/layout/fragment_customer_loan_details.xml, app/src/main/res/layout/layout_alert_message.xml, app/src/main/res/layout/layout_bottom_content.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
=> Feature customer loan details

app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerDeposit.java, app/src/main/java/com/mifos/apache/fineract/data/models/deposit/CustomerDepositAccounts.java, app/src/main/java/com/mifos/apache/fineract/data/services/DepositService.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/CustomerDepositAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/customerdeposit/CustomerDepositFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/depositdetails/CustomerDepositDetailsContract.java, app/src/main/java/com/mifos/apache/fineract/ui/depositdetails/CustomerDepositDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/depositdetails/CustomerDepositDetailsPresenter.java, app/src/main/java/com/mifos/apache/fineract/utils/ConstantKeys.java, app/src/main/res/drawable/ic_account_balance_wallet_black_24dp.xml, app/src/main/res/drawable/ic_close_black_24dp.xml, app/src/main/res/drawable/ic_people_black_24dp.xml, app/src/main/res/layout/fragment_customer_deposit_details.xml, app/src/main/res/values/strings.xml
=> Feature deposit details

app/src/main/java/com/mifos/apache/fineract/ui/login/LoginActivity.java
=> Clear shared preference while logging into app

app/src/main/java/com/mifos/apache/fineract/ui/online/DashboardActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/dashboard/DashboardContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/dashboard/DashboardFragment.java, app/src/main/res/layout/fragment_dashboard.xml, app/src/main/res/values/strings.xml
=> feat: dashboard

app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerCustomer.java, app/src/main/java/com/mifos/apache/fineract/data/models/customer/Command.java, app/src/main/java/com/mifos/apache/fineract/data/services/CustomerService.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/base/MifosBaseBottomSheetDialogFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/base/Toaster.java, app/src/main/java/com/mifos/apache/fineract/ui/online/RefreshUI.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customerdetails/CustomerDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/tasks/TasksBottomSheetContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/tasks/TasksBottomSheetFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/tasks/TasksBottomSheetPresenter.java, app/src/main/java/com/mifos/apache/fineract/utils/AnimationUtils.java, app/src/main/res/drawable/circle_bg_idle.xml, app/src/main/res/drawable/circle_bg_tap.xml, app/src/main/res/drawable/circular_bg.xml, app/src/main/res/drawable/ic_lock_black_24dp.xml, app/src/main/res/drawable/ic_lock_open_black_24dp.xml, app/src/main/res/layout/bottom_sheet_task_list.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
=> feat: Customer tasks, Update customer status

app/src/main/AndroidManifest.xml, app/src/main/java/com/mifos/apache/fineract/data/models/loan/CreditWorthinessFactor.java, app/src/main/java/com/mifos/apache/fineract/data/models/loan/CreditWorthinessSnapshot.java, app/src/main/java/com/mifos/apache/fineract/data/remote/BaseApiManager.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/DebtIncomeReportAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/ViewPagerAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/CustomersFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customerdetails/CustomerDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/debtincomereport/DebtIncomeReportActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/debtincomereport/DebtIncomeReportFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loandetails/CustomerLoanDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/utils/ConstantKeys.java, app/src/main/java/com/mifos/apache/fineract/utils/Utils.java, app/src/main/res/layout/activity_debt_income_report.xml, app/src/main/res/layout/fragment_debt_income_report.xml, app/src/main/res/layout/item_debt_income_report.xml, app/src/main/res/values/strings.xml
=> Feature: loan debts and income

app/src/main/AndroidManifest.xml, app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerCustomer.java, app/src/main/java/com/mifos/apache/fineract/data/models/customer/identification/ExpirationDate.java, app/src/main/java/com/mifos/apache/fineract/data/models/customer/identification/Identification.java, app/src/main/java/com/mifos/apache/fineract/data/services/CustomerService.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/IdentificationAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customerdetails/CustomerDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationlist/IdentificationsActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationlist/IdentificationsContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationlist/IdentificationsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationlist/IdentificationsPresenter.java, app/src/main/java/com/mifos/apache/fineract/utils/DateUtils.java, app/src/main/res/drawable/ic_description_black_24dp.xml, app/src/main/res/layout/fragment_identification_list.xml, app/src/main/res/layout/item_identification.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
=> Feature Customer identification cards list

app/src/main/AndroidManifest.xml, app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerCustomer.java, app/src/main/java/com/mifos/apache/fineract/data/services/CustomerService.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/CreateIdentificationStepAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/IdentificationAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/createidentification/FormIdentificationDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/createidentification/FormOverViewIdentificationFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/createidentification/OnNavigationBarListener.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/createidentification/OverViewContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/createidentification/identificationactivity/CreateIdentificationActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/createidentification/identificationactivity/CreateIdentificationContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/createidentification/identificationactivity/CreateIdentificationPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationlist/IdentificationsFragment.java, app/src/main/res/drawable/ic_event_note_black_24dp.xml, app/src/main/res/layout/activity_create_identification.xml, app/src/main/res/layout/fragment_form_identification_details.xml, app/src/main/res/layout/fragment_form_overview_identification.xml, app/src/main/res/values/strings.xml
=> feat: create new identification card

app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerCustomer.java, app/src/main/java/com/mifos/apache/fineract/data/models/customer/identification/ScanCard.java, app/src/main/java/com/mifos/apache/fineract/data/services/CustomerService.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/IdentificationAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/IdentificationScanAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/createidentification/identificationactivity/CreateIdentificationPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationdetails/IdentificationDetailsContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationdetails/IdentificationDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationdetails/IdentificationDetailsPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationlist/IdentificationsFragment.java, app/src/main/java/com/mifos/apache/fineract/utils/ConstantKeys.java, app/src/main/res/drawable/ic_add_a_photo_black_24dp.xml, app/src/main/res/layout/fragment_identification_details.xml, app/src/main/res/layout/item_identification_scan_card.xml, app/src/main/res/layout/layout_error.xml, app/src/main/res/values/strings.xml
=> feat: identification card details

app/src/main/res/layout/item_identification.xml
=> fix: Identification list item UI enhance

app/src/main/AndroidManifest.xml, app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerCustomer.java, app/src/main/java/com/mifos/apache/fineract/data/services/CustomerService.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationdetails/IdentificationDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/uploadidentificationscan/AddScanIdentificationListener.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/uploadidentificationscan/UploadIdentificationCardBottomSheet.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/uploadidentificationscan/UploadIdentificationCardContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/uploadidentificationscan/UploadIdentificationCardPresenter.java, app/src/main/java/com/mifos/apache/fineract/utils/CheckSelfPermissionAndRequest.java, app/src/main/java/com/mifos/apache/fineract/utils/ConstantKeys.java, app/src/main/java/com/mifos/apache/fineract/utils/MaterialDialog.java, app/src/main/java/com/mifos/apache/fineract/utils/ValidateIdentifierUtil.java, app/src/main/java/com/mifos/apache/fineract/utils/ValidationUtil.java, app/src/main/res/drawable/ic_cancel_black_24dp.xml, app/src/main/res/layout/bottom_sheet_upload_identification_scan_card.xml, app/src/main/res/layout/fragment_identification_details.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, app/src/main/res/xml/filepaths.xml
=> Add identification Scan card document

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/mifos/apache/fineract/data/remote/MifosInterceptor.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ApplicationComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationdetails/IdentificationDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/viewscancard/ViewScanCardActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/viewscancard/ViewScanCardFragment.java, app/src/main/java/com/mifos/apache/fineract/utils/ConstantKeys.java, app/src/main/java/com/mifos/apache/fineract/utils/ImageLoaderUtils.java, app/src/main/res/drawable/ic_autorenew_black_24dp.xml, app/src/main/res/layout/activity_view_scan_card.xml, app/src/main/res/layout/fragment_view_scan_card.xml, app/src/main/res/layout/toolbar.xml
=> feat: view identification scan cards

app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerCustomer.java, app/src/main/java/com/mifos/apache/fineract/data/services/CustomerService.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationdetails/IdentificationDetailsContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationdetails/IdentificationDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationdetails/IdentificationDetailsPresenter.java, app/src/main/java/com/mifos/apache/fineract/utils/Utils.java, app/src/main/res/menu/menu_identification_card.xml, app/src/main/res/values/strings.xml
…Delete identification feature done
Fixes #72
=> feat: Delete identification feature

app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerCustomer.java, app/src/main/java/com/mifos/apache/fineract/data/services/CustomerService.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/CreateIdentificationStepAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/createidentification/Action.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/createidentification/FormIdentificationDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/createidentification/identificationactivity/CreateIdentificationActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/createidentification/identificationactivity/CreateIdentificationContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/createidentification/identificationactivity/CreateIdentificationPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationdetails/IdentificationDetailsContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationdetails/IdentificationDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationlist/IdentificationsFragment.java, app/src/main/java/com/mifos/apache/fineract/utils/ConstantKeys.java, app/src/main/res/values/strings.xml
=> feat: Edit Identification card

app/src/main/res/layout/activity_login.xml
=> fix: show hide login password

app/src/main/java/com/mifos/apache/fineract/ui/online/createcustomer/FormCustomerContactFragment.java
=> FIx: customer contact details

app/src/main/java/com/mifos/apache/fineract/data/models/customer/ContactDetail.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customerdetails/CustomerDetailsContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customerdetails/CustomerDetailsFragment.java, app/src/main/res/layout/fragment_customer_details.xml
=> FIx: NPE customer contact details

app/src/main/java/com/mifos/apache/fineract/ui/online/loanapplication/loandetails/LoanDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/utils/ValidateIdentifierUtil.java, app/src/main/res/layout/fragment_loan_details.xml
=> fix: identifier validation while applying for new loan

app/src/main/AndroidManifest.xml, app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/CreateCustomerStepAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/DashboardActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/createcustomer/FormCustomerContactFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/createcustomer/FormCustomerDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/createcustomer/OnNavigationBarListener.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/createcustomer/customeractivity/CreateCustomerActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/createcustomer/customeractivity/CreateCustomerContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/createcustomer/customeractivity/CreateCustomerPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/createcustomer/formcustomeraddress/FormCustomerAddressContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/createcustomer/formcustomeraddress/FormCustomerAddressFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/createcustomer/formcustomeraddress/FormCustomerAddressPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/customerdetails/CustomerDetailsActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/customerdetails/CustomerDetailsContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/customerdetails/CustomerDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/customerdetails/CustomerDetailsPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/customerlist/CustomersContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/customerlist/CustomersFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/customerlist/CustomersPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/dashboard/DashboardFragment.java
=> refactor: Customer category

app/src/main/java/com/mifos/apache/fineract/ui/online/customer/customerdetails/CustomerDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/utils/StatusUtils.java, app/src/main/res/drawable/ic_file_download_black_24dp.xml, app/src/main/res/layout/fragment_customer_details.xml, app/src/main/res/layout/layout_collapsing_header_view.xml
=> refactor: Customer details UI & UX

app/src/main/java/com/mifos/apache/fineract/ui/online/customer/customerdetails/CustomerDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/utils/ImageLoaderUtils.java, app/src/main/res/layout/fragment_customer_details.xml, app/src/main/res/values/dimens.xml
=> feat: customer profile image in details activity

app/src/main/AndroidManifest.xml, app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/LoanAccountListAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/LoanApplicationStepAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/LoanDebtIncomeAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/customerdetails/CustomerDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanaccountlist/LoanAccountsActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanaccountlist/LoanAccountsContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanaccountlist/LoanAccountsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanaccountlist/LoanAccountsPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/AddDebtIncomeBottomSheet.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/BaseFragmentDebtIncome.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/CreditWorthinessSource.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/LoanDebtIncomeFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/OnBottomSheetDialogListener.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/OnNavigationBarListener.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/loanactivity/LoanApplicationActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/loanactivity/LoanApplicationContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/loanactivity/LoanApplicationPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/loancosigner/LoanCoSignerContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/loancosigner/LoanCoSignerFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/loancosigner/LoanCoSignerPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/loandetails/LoanDetailsContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/loandetails/LoanDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/loandetails/LoanDetailsPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loandetails/CustomerLoanDetailsContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loandetails/CustomerLoanDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loandetails/CustomerLoanDetailsPresenter.java, app/src/main/java/com/mifos/apache/fineract/utils/StatusUtils.java, app/src/main/res/layout/item_customer_loans.xml
=> fix: loan account list UI

app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loandetails/CustomerLoanDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/utils/StatusUtils.java, app/src/main/res/layout/fragment_customer_loan_details.xml, app/src/main/res/menu/menu_loan_account_details.xml, app/src/main/res/values/strings.xml
=> refactor: loan account details UI

app/src/main/java/com/mifos/apache/fineract/data/models/loan/LoanAccount.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/PlannedPaymentAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loanapplication/loandetails/LoanDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/loans/loandetails/CustomerLoanDetailsFragment.java, app/src/main/res/values/strings.xml
=> Fix: loan account details and Planned Payment

app/src/main/java/com/mifos/apache/fineract/ui/adapters/CustomerDepositAdapter.java, app/src/main/res/layout/fragment_customer_deposit.xml, app/src/main/res/layout/item_customer_deposit_accounts.xml
=> Fix: enahance Deposit list UI

app/src/main/AndroidManifest.xml, app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerCustomer.java, app/src/main/java/com/mifos/apache/fineract/data/models/customer/Command.java, app/src/main/java/com/mifos/apache/fineract/data/services/CustomerService.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/CustomerActivitiesAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/customeractivities/CustomerActivitiesActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/customeractivities/CustomerActivitiesContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/customeractivities/CustomerActivitiesFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/customeractivities/CustomerActivitiesPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/customerdetails/CustomerDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/tasks/TasksBottomSheetFragment.java, app/src/main/java/com/mifos/apache/fineract/utils/DateUtils.java, app/src/main/java/com/mifos/apache/fineract/utils/StatusUtils.java, app/src/main/res/layout/fragment_customer_activities.xml, app/src/main/res/layout/item_customer_activities.xml, app/src/main/res/values/strings.xml
=> Feature: customer activities

app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerCustomer.java, app/src/main/java/com/mifos/apache/fineract/data/services/CustomerService.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/createidentification/identificationactivity/CreateIdentificationActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationdetails/IdentificationDetailsContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationdetails/IdentificationDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/identification/identificationdetails/IdentificationDetailsPresenter.java, app/src/main/res/values/strings.xml
=> Fix identification feature

app/src/main/AndroidManifest.xml, app/src/main/java/com/mifos/apache/fineract/ui/online/customer/createcustomer/formcustomeraddress/FormCustomerAddressFragment.java, app/src/main/java/com/mifos/apache/fineract/utils/ConstantKeys.java
=> fix: while create client and chnage to landscap token null

app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/online/DashboardActivity.java, app/src/main/res/drawable/ic_input_black_24dp.xml, app/src/main/res/menu/menu_navigation_drawer.xml, app/src/main/res/values/strings.xml
=> Feature: logout from app

app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/online/DashboardActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/customerdetails/CustomerDetailsActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/customerdetails/CustomerDetailsContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/customerdetails/CustomerDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/customerlist/CustomersFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/customertasks/CustomerTasksBottomSheetContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/customertasks/CustomerTasksBottomSheetFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/customertasks/CustomerTasksBottomSheetPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/customertasks/OnTasksChangeListener.java, app/src/main/java/com/mifos/apache/fineract/utils/ConstantKeys.java, app/src/main/res/layout/bottom_sheet_task_list.xml
=> Fix: customer status in Detail page and List

app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerCustomer.java, app/src/main/java/com/mifos/apache/fineract/data/models/customer/Address.java, app/src/main/java/com/mifos/apache/fineract/data/models/customer/ContactDetail.java, app/src/main/java/com/mifos/apache/fineract/data/models/customer/Customer.java, app/src/main/java/com/mifos/apache/fineract/data/models/customer/DateOfBirth.java, app/src/main/java/com/mifos/apache/fineract/data/services/CustomerService.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/CreateCustomerStepAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/createcustomer/CustomerAction.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/createcustomer/FormCustomerContactFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/createcustomer/FormCustomerDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/createcustomer/customeractivity/CreateCustomerActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/createcustomer/customeractivity/CreateCustomerContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/createcustomer/customeractivity/CreateCustomerPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/createcustomer/formcustomeraddress/FormCustomerAddressFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/customerdetails/CustomerDetailsFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/customers/customerlist/CustomersFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/dashboard/DashboardFragment.java, app/src/main/java/com/mifos/apache/fineract/utils/ConstantKeys.java, app/src/main/res/layout/fragment_customer_details.xml, app/src/main/res/values/strings.xml
=> Feature: Edit customer

app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerAuth.java, app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerCustomer.java, app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerDeposit.java, app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerIndividualLending.java, app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerLoans.java, app/src/main/java/com/mifos/apache/fineract/data/datamanager/MifosBaseDataManager.java, app/src/main/java/com/mifos/apache/fineract/exceptions/ExceptionStatusCode.java
=> Refresh access token globally if 403 exception occur 

app/src/main/java/com/mifos/apache/fineract/data/datamanager/MifosBaseDataManager.java, app/src/main/java/com/mifos/apache/fineract/exceptions/ExceptionStatusCode.java
=> Fix: Completable response on error and typo

app/src/main/java/com/mifos/apache/fineract/data/datamanager/DataManagerRoles.java, app/src/main/java/com/mifos/apache/fineract/data/models/rolesandpermission/AllowedOperation.java, app/src/main/java/com/mifos/apache/fineract/data/models/rolesandpermission/Permission.java, app/src/main/java/com/mifos/apache/fineract/data/models/rolesandpermission/Role.java, app/src/main/java/com/mifos/apache/fineract/data/remote/BaseApiManager.java, app/src/main/java/com/mifos/apache/fineract/data/services/RolesService.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ActivityComponent.java, app/src/main/java/com/mifos/apache/fineract/injection/component/ApplicationComponent.java, app/src/main/java/com/mifos/apache/fineract/ui/adapters/RolesAdapter.java, app/src/main/java/com/mifos/apache/fineract/ui/online/DashboardActivity.java, app/src/main/java/com/mifos/apache/fineract/ui/online/roles/roleslist/RolesContract.java, app/src/main/java/com/mifos/apache/fineract/ui/online/roles/roleslist/RolesFragment.java, app/src/main/java/com/mifos/apache/fineract/ui/online/roles/roleslist/RolesPresenter.java, app/src/main/java/com/mifos/apache/fineract/ui/views/TextDrawable.java, app/src/main/java/com/mifos/apache/fineract/utils/ColorGenerator.java, app/src/main/java/com/mifos/apache/fineract/utils/ScrollFabBehavior.java, app/src/main/res/layout/fragment_roles_list.xml, app/src/main/res/layout/item_roles.xml, app/src/main/res/menu/menu_navigation_drawer.xml, app/src/main/res/values/strings.xml, config/quality/findbugs/android-exclude-filter.xml
=> Feat: Roles and Permission

app/src/main/res/layout/item_customer.xml
=> refactor: Enhance client list

app/src/main/java/com/mifos/apache/fineract/data/remote/BaseApiManager.java, app/src/main/java/com/mifos/apache/fineract/data/remote/BaseUrl.java, app/src/main/java/com/mifos/apache/fineract/data/remote/MifosOkHttpClient.java
=> Feature: Add SSL certificate and HTTP to HTTPS

app/src/main/res/layout/fragment_customer_deposit.xml, app/src/main/res/layout/fragment_customer_list.xml, app/src/main/res/layout/fragment_customer_loans.xml, app/src/main/res/layout/fragment_identification_details.xml, app/src/main/res/layout/fragment_identification_list.xml
=> Fix: Hide Fab Button while scrolling down

app/src/main/java/org/apache/fineract/ui/online/customers/customerdetails/CustomerDetailsFragment.java, app/src/main/res/layout/fragment_customer_details.xml
=> refactor: Enhance UX while loading customer details

.travis.yml, README.md, app/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> chore: update build tools and gradle version

app/src/main/java/org/apache/fineract/ui/online/roles/roleslist/RolesPresenter.java
=> Fix roles fragment issue

app/src/main/AndroidManifest.xml
=> fix: enables scrolling while creating customer

app/src/main/java/org/apache/fineract/ui/online/customers/createcustomer/formcustomeraddress/FormCustomerAddressFragment.java
Fixes #176
**After making the change -**
=> fix: List of countries keeps on being displayed even after selecting one from the list

app/src/main/java/org/apache/fineract/ui/online/customers/createcustomer/FormCustomerDetailsFragment.java
Fixes #175 
**After making the change-**
=> fix : Invalid values are accepted for the date of birth of a customer

app/src/main/java/org/apache/fineract/ui/online/customers/customerdetails/CustomerDetailsFragment.java
=> Fix:Inconsistent Assigned Employee status

app/src/main/java/org/apache/fineract/ui/online/customers/createcustomer/FormCustomerDetailsFragment.java, app/src/main/res/values/styles.xml
=> Fix: Ok/Cancel buttons visible in DatePicker
